### ISSUE TITLE
We should default to a proper url 

### ISSUE THREAD

**Issue by dan-Codefresh** [codefresh-io/argocd-agent#60]
We should default to the internal formatted url when adding the server. It's better than example.com and should work brilliantly 99% of the time. We should also change the example based on the namespace they put in the previous question so it's always right. 

<img width="1841" alt="Screen Shot 2020-11-03 at 1 54 33 AM" src="https://user-images.githubusercontent.com/29411043/97965483-aadf3280-1d77-11eb-9b00-608992a6d39e.png">

Internal formatted url `https://argocd-server.argocd.svc.cluster.local`

or `https://argocd-server.NAMESPACE.svc.cluster.local`

**Comment by dan-Codefresh** [comment]
wdyt @pasha-codefresh ?

**Comment by pasha-codefresh** [comment]
good point @dan-Codefresh , we will change it
